version: '3.8'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: serviceUser123
      MYSQL_DATABASE: user-service
      MYSQL_USER: heinwai
      MYSQL_PASSWORD: user123
    ports:
      - "3307:3306"
